### PR TITLE
SCMOD-7336: Admin caused failures now retried

### PR DESCRIPTION
**Pull request by Anthony-McGreevy**
https://portal.digitalsafe.net/browse/SCMOD-7336

### CODE REVIEW

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
The change looks fine but surely it shouldn't be limited to just report_complete.

**Comment by Anthony-McGreevy** [comment]
@dermot-hardy This has now been updated to include the other methods reaching out to the database

**Comment by Anthony-McGreevy** [comment]
@dermot-hardy Can you merge this if you are happy with the changes. For QA of this ticket should Michael also verify the retry behavior by taking down Baltra's Postgres instance? Or is it ok to just verify that all tests are passing and the worker continues to work as it did before?

**Comment by Anthony-McGreevy** [comment]
Build: http://sou-jenkins2.hpeswlab.net/job/JobService/view/Developer/job/JobService~job-service~SCMOD-7336~CI/

**Review by dermot-hardy — APPROVED** [review]

**Comment by dermot-hardy** [comment]
He should test by taking down the instance.

**Pull request merged**
