### PR TITLE
CAF-2960: Update Postgres Driver to v42.1.1

### PR DESCRIPTION
**Pull request by CJComac**

### CODE REVIEW

**Comment by glucy** [comment]
This looks fine can you create a Developer Build and ensure everything is ok?

**Comment by glucy** [comment]
Execute mvn clean
Run a search for 2.1.0-SNAPSHOT:  grep -r "2.1.0-SNAPSHOT" *
Make sure all 2.1.0's have been appropriately converted to 2.0.1

**Review by glucy — APPROVED** [review]

**Comment by CJComac** [comment]
Dev build OK (failing for unrelated reason): http://sou-jenkins2.hpeswlab.net/job/JobService/view/Developer/job/JobService~job-service~CAF-2960_Update_Postgres_Driver~CI/

No occurrences of 2.1.0-SNAPSHOT found

**Review by CJComac — COMMENTED** [review]
No longer required (31.05.17): The java-postgres base container (currently being moved to caf-common: https://github.com/CAFapi/caf-common/pull/25) will need updated to use Postgres 9.6, released and then the following line will need updated before merging: https://github.com/JobService/job-service/blob/CAF-2960_Update_Postgres_Driver/job-service-postgres-container/pom.xml#L79

**Pull request merged**
