### PR TITLE
SCMOD-10185: Remove early createProcedure changesets

### PR DESCRIPTION
**Pull request by dermot-hardy**
https://portal.digitalsafe.net/browse/SCMOD-10185

- These are done in the procedures/changeset.xml

### CODE REVIEW

**Comment by dermot-hardy** [comment]
@dgibson-microfocus I know you looked at this before.  Is there any reason this can't be done?

**Comment by dgibson-microfocus** [comment]
It won't cause any issues with the creation of the stored procedures, but won't this completely break the upgrade? You've modified the checksum of several steps and a 3.2 db will have entries for steps that no longer exist.

**Comment by dermot-hardy** [comment]
What checksums have I modified?  Aren't the checksums calculated at the changeset level?  I've only removed changesets.

**Comment by dgibson-microfocus** [comment]
> 
> 
> What checksums have I modified? Aren't the checksums calculated at the changeset level? I've only removed changesets.

Of course, sorry. I was thinking of flyway which builds a checksum of the whole file.

**Review by dgibson-microfocus — APPROVED** [review]
Assuming upgrade still works

**Pull request merged**
