### PR TITLE
SCMOD-4372: Updated to produce no response

### PR DESCRIPTION
**Pull request by Anthony-McGreevy**
https://jira.autonomy.com/browse/SCMOD-4372

### CODE REVIEW

**Review by dermot-hardy — APPROVED** [review]
Change looks good but we need a Jira for this

**Comment by dermot-hardy** [comment]
We're probably going to want to update default queue name and configuration in tandem with this.

**Comment by Anthony-McGreevy** [comment]
SCMOD-4372 has been raised to cover this issue.

**Comment by Anthony-McGreevy** [comment]
workers default output queue is the workers name plus -err or just worker-err if the workers name cannot be found.

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
