### PR TITLE
jobtracking specific log activation

### PR DESCRIPTION
**Pull request by xbreizh**
That specific log will provide details on the subtasks being passed into the db

### CODE REVIEW

**Review by dermot-hardy — APPROVED** [review]
You're putting a PR in for this but we're not actually going to merge it, right?

**Comment by dermot-hardy** [comment]
This is just to help with investigating [SCMOD-11892](https://portal.digitalsafe.net/browse/SCMOD-11892).

**Comment by xbreizh** [comment]
> This is just to help with investigating [SCMOD-11892](https://portal.digitalsafe.net/browse/SCMOD-11892).

**Comment by xbreizh** [comment]
> You're putting a PR in for this but we're not actually going to merge it, right?

True, I closed it. Nothing that should modify the build result anyway

**Pull request closed without merging**
